"""
Catalog of webapps for the 'Apps' view.
"""

from typing import TypedDict


class AppEntry(TypedDict):
    label: str
    url: str
    port: int | None
    whatItIs: str
    whatYouCanDo: str
    startScript: str


APPS_CATALOG: list[AppEntry] = [
    {
        "label": "Alexa",
        "url": "#",
        "port": None,
        "whatItIs": "Specialized Alexa MCP service for enhanced technical workflows.",
        "whatYouCanDo": "Enable autonomous alexa operations and data integration within your fleet.",
        "startScript": "alexa-mcp/web_sota/start.ps1",
    },
    {
        "label": "Avatar",
        "url": "http://127.0.0.1:10710",
        "port": 10710,
        "whatItIs": "Web dashboard",
        "whatYouCanDo": "Enable autonomous avatar operations and data integration within your fleet.",
        "startScript": "avatar-mcp/web_sota/start.ps1",
    },
    {
        "label": "Beyondcompare",
        "url": "#",
        "port": None,
        "whatItIs": "Specialized Beyondcompare MCP service for enhanced technical workflows.",
        "whatYouCanDo": "Enable autonomous beyondcompare operations and data integration within your fleet.",
        "startScript": "beyondcompare-mcp/web_sota/start.ps1",
    },
    {
        "label": "Bookmarks",
        "url": "#",
        "port": None,
        "whatItIs": "Specialized Bookmarks MCP service for enhanced technical workflows.",
        "whatYouCanDo": "Enable autonomous bookmarks operations and data integration within your fleet.",
        "startScript": "bookmarks-mcp/web_sota/start.ps1",
    },
    {
        "label": "Calibre",
        "url": "http://127.0.0.1:10721",
        "port": 10721,
        "whatItIs": "Frontend",
        "whatYouCanDo": "Enable autonomous calibre operations and data integration within your fleet.",
        "startScript": "calibre-mcp/webapp/start.ps1",
    },
    {
        "label": "Dark App Factory",
        "url": "http://127.0.0.1:10738",
        "port": 10738,
        "whatItIs": "Web dashboard",
        "whatYouCanDo": "Enable autonomous dark app factory operations and data integration within your fleet.",
        "startScript": "dark-app-factory/web/start.ps1",
    },
    {
        "label": "Database Operations",
        "url": "http://127.0.0.1:10708",
        "port": 10708,
        "whatItIs": "Web dashboard",
        "whatYouCanDo": "Enable autonomous database operations operations and data integration within your fleet.",
        "startScript": "database-operations-mcp/web_sota/start.ps1",
    },
    {
        "label": "Davinci Resolve",
        "url": "#",
        "port": None,
        "whatItIs": "Specialized Davinci Resolve MCP service for enhanced technical workflows.",
        "whatYouCanDo": "Enable autonomous davinci resolve operations and data integration within your fleet.",
        "startScript": "davinci-resolve-mcp/web_sota/start.ps1",
    },
    {
        "label": "Devices",
        "url": "http://127.0.0.1:10716",
        "port": 10716,
        "whatItIs": "Web dashboard",
        "whatYouCanDo": "Enable autonomous devices operations and data integration within your fleet.",
        "startScript": "devices-mcp/web-sota/start.ps1",
    },
    {
        "label": "Directmedia",
        "url": "#",
        "port": None,
        "whatItIs": "Specialized Directmedia MCP service for enhanced technical workflows.",
        "whatYouCanDo": "Enable autonomous directmedia operations and data integration within your fleet.",
        "startScript": "directmedia-mcp/web_sota/start.ps1",
    },
    {
        "label": "Docker",
        "url": "http://127.0.0.1:10784",
        "port": 10784,
        "whatItIs": "MCP API",
        "whatYouCanDo": "Enable autonomous docker operations and data integration within your fleet.",
        "startScript": "docker-mcp/web_sota/start.ps1",
    },
    {
        "label": "Email",
        "url": "#",
        "port": None,
        "whatItIs": "Specialized Email MCP service for enhanced technical workflows.",
        "whatYouCanDo": "Enable autonomous email operations and data integration within your fleet.",
        "startScript": "email-mcp/web_sota/start.ps1",
    },
    {
        "label": "Federation Hub",
        "url": "http://127.0.0.1:10856",
        "port": 10856,
        "whatItIs": "Unified orchestration dashboard for MCP servers; bridge 10857.",
        "whatYouCanDo": "Discover, manage, and interact with multiple MCP servers; mesh and peer links.",
        "startScript": "mcp-federation-hub/webapp/start.ps1",
    },
    {
        "label": "Fastsearch",
        "url": "#",
        "port": None,
        "whatItIs": "Specialized Fastsearch MCP service for enhanced technical workflows.",
        "whatYouCanDo": "Enable autonomous fastsearch operations and data integration within your fleet.",
        "startScript": "fastsearch-mcp/web_sota/start.ps1",
    },
    {
        "label": "Filesystem",
        "url": "http://127.0.0.1:10743",
        "port": 10743,
        "whatItIs": "Frontend (was 13001)",
        "whatYouCanDo": "Enable autonomous filesystem operations and data integration within your fleet.",
        "startScript": "filesystem-mcp/webapp/start.bat",
    },
    {
        "label": "Git Github",
        "url": "http://127.0.0.1:10702",
        "port": 10702,
        "whatItIs": "Git GitHub Hub",
        "whatYouCanDo": "Enable autonomous git github operations and data integration within your fleet.",
        "startScript": "git-github-mcp/web/start.ps1",
    },
    {
        "label": "Gtfs",
        "url": "#",
        "port": None,
        "whatItIs": "Specialized Gtfs MCP service for enhanced technical workflows.",
        "whatYouCanDo": "Enable autonomous gtfs operations and data integration within your fleet.",
        "startScript": "gtfs-mcp/web_sota/start.ps1",
    },
    {
        "label": "Handbrake",
        "url": "#",
        "port": None,
        "whatItIs": "Specialized Handbrake MCP service for enhanced technical workflows.",
        "whatYouCanDo": "Enable autonomous handbrake operations and data integration within your fleet.",
        "startScript": "handbrake-mcp/web_sota/start.ps1",
    },
    {
        "label": "Home Assistant",
        "url": "http://127.0.0.1:10782",
        "port": 10782,
        "whatItIs": "MCP HTTP",
        "whatYouCanDo": "Enable autonomous home assistant operations and data integration within your fleet.",
        "startScript": "home-assistant-mcp/web_sota/start.ps1",
    },
    {
        "label": "Immich",
        "url": "#",
        "port": None,
        "whatItIs": "Specialized Immich MCP service for enhanced technical workflows.",
        "whatYouCanDo": "Enable autonomous immich operations and data integration within your fleet.",
        "startScript": "immich-mcp/web_sota/start.ps1",
    },
    {
        "label": "Inkscape",
        "url": "#",
        "port": None,
        "whatItIs": "Specialized Inkscape MCP service for enhanced technical workflows.",
        "whatYouCanDo": "Enable autonomous inkscape operations and data integration within your fleet.",
        "startScript": "inkscape-mcp/web_sota/start.ps1",
    },
    {
        "label": "Kyutai",
        "url": "http://127.0.0.1:10925",
        "port": 10925,
        "whatItIs": "Kyutai Moshi operator console; API 10924, MCP HTTP 10926.",
        "whatYouCanDo": "Voice session control, Glom-On local LLM, moshi_ops MCP tools.",
        "startScript": "kyutai-mcp/webapp/start.ps1",
    },
    {
        "label": "LeWM",
        "url": "http://127.0.0.1:10928",
        "port": 10928,
        "whatItIs": "LeWorldModel (JEPA) MCP bridge; API 10927, MCP /mcp on API.",
        "whatYouCanDo": "Train/infer prep, agentic workflow, skills; set LEWM_UPSTREAM_ROOT to lucas-maes/le-wm clone.",
        "startScript": "lewm-mcp/webapp/start.ps1",
    },
    {
        "label": "Llm Txt",
        "url": "#",
        "port": None,
        "whatItIs": "Specialized Llm Txt MCP service for enhanced technical workflows.",
        "whatYouCanDo": "Enable autonomous llm txt operations and data integration within your fleet.",
        "startScript": "llm-txt-mcp/web_sota/start.ps1",
    },
    {
        "label": "Local Llm",
        "url": "#",
        "port": None,
        "whatItIs": "Specialized Local Llm MCP service for enhanced technical workflows.",
        "whatYouCanDo": "Enable autonomous local llm operations and data integration within your fleet.",
        "startScript": "local-llm-mcp/web_sota/start.ps1",
    },
    {
        "label": "Mcp Central Docs",
        "url": "http://127.0.0.1:11033",
        "port": 11033,
        "whatItIs": "Public Docs Hub (documentation-mcp)",
        "whatYouCanDo": "Enable autonomous mcp central docs operations and data integration within your fleet.",
        "startScript": "mcp-central-docs/start.ps1",
    },
    {
        "label": "Mcp Studio",
        "url": "http://127.0.0.1:10725",
        "port": 10725,
        "whatItIs": "Frontend",
        "whatYouCanDo": "Enable autonomous mcp studio operations and data integration within your fleet.",
        "startScript": "mcp-studio/start.ps1",
    },
    {
        "label": "Meta_Mcp",
        "url": "http://127.0.0.1:10719",
        "port": 10719,
        "whatItIs": "Frontend",
        "whatYouCanDo": "Enable autonomous meta_mcp operations and data integration within your fleet.",
        "startScript": "meta_mcp/start.bat",
    },
    {
        "label": "Moltbot",
        "url": "http://127.0.0.1:10730",
        "port": 10730,
        "whatItIs": "Webapp",
        "whatYouCanDo": "Enable autonomous moltbot operations and data integration within your fleet.",
        "startScript": "moltbot-mcp/web_sota/start.ps1",
    },
    {
        "label": "Monitoring",
        "url": "http://127.0.0.1:10786",
        "port": 10786,
        "whatItIs": "MCP API",
        "whatYouCanDo": "Enable autonomous monitoring operations and data integration within your fleet.",
        "startScript": "monitoring-mcp/web_sota/start.ps1",
    },
    {
        "label": "Multi Backup",
        "url": "http://127.0.0.1:10798",
        "port": 10798,
        "whatItIs": "Multi-method backup MCP server - System backups, ZIP archives, and Git/GitHub integration.",
        "whatYouCanDo": "Trigger high-impact Nuclear Backups and manage Hasleo system images.",
        "startScript": "multi-backup-mcp/web_sota/start.ps1",
    },
    {
        "label": "Mywienerlinien",
        "url": "http://127.0.0.1:10722",
        "port": 10722,
        "whatItIs": "Frontend",
        "whatYouCanDo": "Enable autonomous mywienerlinien operations and data integration within your fleet.",
        "startScript": "mywienerlinien/start.ps1",
    },
    {
        "label": "Nest Protect",
        "url": "http://127.0.0.1:10752",
        "port": 10752,
        "whatItIs": "Frontend (was 7770)",
        "whatYouCanDo": "Enable autonomous nest protect operations and data integration within your fleet.",
        "startScript": "nest-protect-mcp/web_sota/start.ps1",
    },
    {
        "label": "Netatmo Weather",
        "url": "#",
        "port": None,
        "whatItIs": "Specialized Netatmo Weather MCP service for enhanced technical workflows.",
        "whatYouCanDo": "Enable autonomous netatmo weather operations and data integration within your fleet.",
        "startScript": "netatmo-weather-mcp/web_sota/start.ps1",
    },
    {
        "label": "Notepadpp",
        "url": "#",
        "port": None,
        "whatItIs": "Specialized Notepadpp MCP service for enhanced technical workflows.",
        "whatYouCanDo": "Enable autonomous notepadpp operations and data integration within your fleet.",
        "startScript": "notepadpp-mcp/web_sota/start.ps1",
    },
    {
        "label": "Notion",
        "url": "#",
        "port": None,
        "whatItIs": "Specialized Notion MCP service for enhanced technical workflows.",
        "whatYouCanDo": "Enable autonomous notion operations and data integration within your fleet.",
        "startScript": "notion-mcp/web_sota/start.ps1",
    },
    {
        "label": "Nuki",
        "url": "http://127.0.0.1:10892",
        "port": 10892,
        "whatItIs": "Web dashboard",
        "whatYouCanDo": "Nuki Smart Lock MCP via Home Assistant; control locks and openers.",
        "startScript": "nuki-mcp/web_sota/start.ps1",
    },
    {
        "label": "Obs",
        "url": "#",
        "port": None,
        "whatItIs": "Specialized Obs MCP service for enhanced technical workflows.",
        "whatYouCanDo": "Enable autonomous obs operations and data integration within your fleet.",
        "startScript": "obs-mcp/web_sota/start.ps1",
    },
    {
        "label": "Observability",
        "url": "#",
        "port": None,
        "whatItIs": "Specialized Observability MCP service for enhanced technical workflows.",
        "whatYouCanDo": "Enable autonomous observability operations and data integration within your fleet.",
        "startScript": "observability-mcp/web_sota/start.ps1",
    },
    {
        "label": "Obsidian",
        "url": "#",
        "port": None,
        "whatItIs": "Specialized Obsidian MCP service for enhanced technical workflows.",
        "whatYouCanDo": "Enable autonomous obsidian operations and data integration within your fleet.",
        "startScript": "obsidian-mcp/web_sota/start.ps1",
    },
    {
        "label": "Ocr",
        "url": "#",
        "port": None,
        "whatItIs": "Specialized Ocr MCP service for enhanced technical workflows.",
        "whatYouCanDo": "Enable autonomous ocr operations and data integration within your fleet.",
        "startScript": "ocr-mcp/web_sota/start.ps1",
    },
    {
        "label": "Onenote",
        "url": "#",
        "port": None,
        "whatItIs": "Specialized Onenote MCP service for enhanced technical workflows.",
        "whatYouCanDo": "Enable autonomous onenote operations and data integration within your fleet.",
        "startScript": "onenote-mcp/web_sota/start.ps1",
    },
    {
        "label": "OpenManus",
        "url": "https://github.com/FoundationAgents/OpenManus",
        "port": None,
        "whatItIs": "FOSS CLI agent (MetaGPT lineage); 100% local LLM when config.toml uses Ollama/LM Studio/etc. MCP **client** via mcp.json. Fleet: openmanus-mcp (FastMCP 3.1) + SOTA webapp; $0 Manus.im subscription.",
        "whatYouCanDo": "Run python main.py; attach fleet MCP servers; openmanus-mcp wraps CLI for Cursor + webapp ports 10768/10769. Doc: integrations/openmanus.md.",
        "startScript": "FoundationAgents/OpenManus: uv/pip install; local LLM in config.toml; python main.py",
    },
    {
        "label": "Openclaw Molt",
        "url": "http://127.0.0.1:10764",
        "port": 10764,
        "whatItIs": "Frontend (was 5180)",
        "whatYouCanDo": "Enable autonomous openclaw molt operations and data integration within your fleet.",
        "startScript": "openclaw-molt-mcp/web_sota/start.ps1",
    },
    {
        "label": "Osc",
        "url": "#",
        "port": None,
        "whatItIs": "Specialized Osc MCP service for enhanced technical workflows.",
        "whatYouCanDo": "Enable autonomous osc operations and data integration within your fleet.",
        "startScript": "osc-mcp/web_sota/start.ps1",
    },
    {
        "label": "Pinokio",
        "url": "#",
        "port": None,
        "whatItIs": "Specialized Pinokio MCP service for enhanced technical workflows.",
        "whatYouCanDo": "Enable autonomous pinokio operations and data integration within your fleet.",
        "startScript": "pinokio-mcp/web_sota/start.ps1",
    },
    {
        "label": "Plex",
        "url": "http://127.0.0.1:10741",
        "port": 10741,
        "whatItIs": "Webapp frontend",
        "whatYouCanDo": "Enable autonomous plex operations and data integration within your fleet.",
        "startScript": "plex-mcp/webapp/start.ps1",
    },
    {
        "label": "Pywinauto",
        "url": "#",
        "port": None,
        "whatItIs": "Specialized Pywinauto MCP service for enhanced technical workflows.",
        "whatYouCanDo": "Enable autonomous pywinauto operations and data integration within your fleet.",
        "startScript": "pywinauto-mcp/web_sota/start.ps1",
    },
    {
        "label": "Qbt",
        "url": "#",
        "port": None,
        "whatItIs": "Specialized Qbt MCP service for enhanced technical workflows.",
        "whatYouCanDo": "Enable autonomous qbt operations and data integration within your fleet.",
        "startScript": "qbt-mcp/start.bat",
    },
    {
        "label": "Readly",
        "url": "#",
        "port": None,
        "whatItIs": "Specialized Readly MCP service for enhanced technical workflows.",
        "whatYouCanDo": "Enable autonomous readly operations and data integration within your fleet.",
        "startScript": "readly-mcp/start.bat",
    },
    {
        "label": "Reaper",
        "url": "#",
        "port": None,
        "whatItIs": "Specialized Reaper MCP service for enhanced technical workflows.",
        "whatYouCanDo": "Enable autonomous reaper operations and data integration within your fleet.",
        "startScript": "reaper-mcp/web_sota/start.ps1",
    },
    {
        "label": "Repomix",
        "url": "#",
        "port": None,
        "whatItIs": "Specialized Repomix MCP service for enhanced technical workflows.",
        "whatYouCanDo": "Enable autonomous repomix operations and data integration within your fleet.",
        "startScript": "repomix-mcp/web_sota/start.ps1",
    },
    {
        "label": "Resolume",
        "url": "#",
        "port": None,
        "whatItIs": "Specialized Resolume MCP service for enhanced technical workflows.",
        "whatYouCanDo": "Enable autonomous resolume operations and data integration within your fleet.",
        "startScript": "resolume-mcp/web_sota/start.ps1",
    },
    {
        "label": "Resonite",
        "url": "http://127.0.0.1:10714",
        "port": 10714,
        "whatItIs": "Web dashboard",
        "whatYouCanDo": "Enable autonomous resonite operations and data integration within your fleet.",
        "startScript": "resonite-mcp/web_sota/start.ps1",
    },
    {
        "label": "Reversing",
        "url": "http://127.0.0.1:10750",
        "port": 10750,
        "whatItIs": "Webapp (was 5000)",
        "whatYouCanDo": "Enable autonomous reversing operations and data integration within your fleet.",
        "startScript": "reversing-mcp/web_sota/start.ps1",
    },
    {
        "label": "Ring",
        "url": "http://127.0.0.1:10728",
        "port": 10728,
        "whatItIs": "Web dashboard",
        "whatYouCanDo": "Enable autonomous ring operations and data integration within your fleet.",
        "startScript": "ring-mcp/web_sota/start.ps1",
    },
    {
        "label": "Robotics",
        "url": "http://127.0.0.1:10706",
        "port": 10706,
        "whatItIs": "Web dashboard",
        "whatYouCanDo": "Enable autonomous robotics operations and data integration within your fleet.",
        "startScript": "robotics-mcp/webapp/start.ps1",
    },
    {
        "label": "Rustdesk",
        "url": "#",
        "port": None,
        "whatItIs": "Specialized Rustdesk MCP service for enhanced technical workflows.",
        "whatYouCanDo": "Enable autonomous rustdesk operations and data integration within your fleet.",
        "startScript": "rustdesk-mcp/web_sota/start.ps1",
    },
    {
        "label": "Sakana",
        "url": "http://127.0.0.1:10862",
        "port": 10862,
        "whatItIs": "Sakana AI Scientist v2 research dashboard; backend 10863.",
        "whatYouCanDo": "Ideate, execute, and review autonomous research loops with Docker sandboxing.",
        "startScript": "sakana-mcp/webapp/start.ps1",
    },
    {
        "label": "Sdr",
        "url": "#",
        "port": None,
        "whatItIs": "Specialized Sdr MCP service for enhanced technical workflows.",
        "whatYouCanDo": "Enable autonomous sdr operations and data integration within your fleet.",
        "startScript": "sdr-mcp/web_sota/start.ps1",
    },
    {
        "label": "Songgeneration",
        "url": "#",
        "port": None,
        "whatItIs": "LeVo 2 / SG2 music MCP (SongGeneration-Studio): local open-weight generation, dual-track WAV; see docs://lyria-vs-sg2 vs Gemini Lyria 3 Pro.",
        "whatYouCanDo": "Generate with SG2 tags; optional style prompt; compare cloud Lyria (~$0.08/song—verify) vs local GPU path.",
        "startScript": "songgeneration-mcp/web_sota/start.ps1",
    },
    {
        "label": "Speech",
        "url": "http://127.0.0.1:10917",
        "port": 10917,
        "whatItIs": "SOTA Speech interface for Hume AI EVI & Octave.",
        "whatYouCanDo": "Enable emotionally intelligent real-time voice and high-fidelity TTS synthesis.",
        "startScript": "speech-mcp/web/start.ps1",
    },
    {
        "label": "Suno",
        "url": "#",
        "port": None,
        "whatItIs": "Specialized Suno MCP service for enhanced technical workflows.",
        "whatYouCanDo": "Enable autonomous suno operations and data integration within your fleet.",
        "startScript": "suno-mcp/web_sota/start.ps1",
    },
    {
        "label": "System Admin",
        "url": "#",
        "port": None,
        "whatItIs": "Specialized System Admin MCP service for enhanced technical workflows.",
        "whatYouCanDo": "Enable autonomous system admin operations and data integration within your fleet.",
        "startScript": "system-admin-mcp/web_sota/start.ps1",
    },
    {
        "label": "Tailscale",
        "url": "#",
        "port": None,
        "whatItIs": "Specialized Tailscale MCP service for enhanced technical workflows.",
        "whatYouCanDo": "Enable autonomous tailscale operations and data integration within your fleet.",
        "startScript": "tailscale-mcp/web_sota/start.ps1",
    },
    {
        "label": "Unity3D",
        "url": "#",
        "port": None,
        "whatItIs": "Specialized Unity3D MCP service for enhanced technical workflows.",
        "whatYouCanDo": "Enable autonomous unity3d operations and data integration within your fleet.",
        "startScript": "unity3d-mcp/web_sota/start.ps1",
    },
    {
        "label": "Universal Actuator",
        "url": "#",
        "port": None,
        "whatItIs": "Specialized Universal Actuator MCP service for enhanced technical workflows.",
        "whatYouCanDo": "Enable autonomous universal actuator operations and data integration within your fleet.",
        "startScript": "universal-actuator-mcp/web_sota/start.ps1",
    },
    {
        "label": "Vbox",
        "url": "#",
        "port": None,
        "whatItIs": "Specialized Vbox MCP service for enhanced technical workflows.",
        "whatYouCanDo": "Enable autonomous vbox operations and data integration within your fleet.",
        "startScript": "vbox-mcp/web_sota/start.ps1",
    },
    {
        "label": "Vienna Live",
        "url": "#",
        "port": None,
        "whatItIs": "Specialized Vienna Live MCP service for enhanced technical workflows.",
        "whatYouCanDo": "Enable autonomous vienna live operations and data integration within your fleet.",
        "startScript": "vienna-live-mcp/web_sota/start.ps1",
    },
    {
        "label": "Virtualdj",
        "url": "#",
        "port": None,
        "whatItIs": "Specialized Virtualdj MCP service for enhanced technical workflows.",
        "whatYouCanDo": "Enable autonomous virtualdj operations and data integration within your fleet.",
        "startScript": "virtualdj-mcp/web_sota/start.ps1",
    },
    {
        "label": "Virtualization",
        "url": "http://127.0.0.1:10700",
        "port": 10700,
        "whatItIs": "Web dashboard",
        "whatYouCanDo": "Enable autonomous virtualization operations and data integration within your fleet.",
        "startScript": "virtualization-mcp/webapp/start.ps1",
    },
    {
        "label": "Vrchat",
        "url": "http://127.0.0.1:10712",
        "port": 10712,
        "whatItIs": "Web dashboard",
        "whatYouCanDo": "Enable autonomous vrchat operations and data integration within your fleet.",
        "startScript": "vrchat-mcp/start.ps1",
    },
    {
        "label": "Vroidstudio",
        "url": "#",
        "port": None,
        "whatItIs": "Specialized Vroidstudio MCP service for enhanced technical workflows.",
        "whatYouCanDo": "Enable autonomous vroidstudio operations and data integration within your fleet.",
        "startScript": "vroidstudio-mcp/web_sota/start.ps1",
    },
    {
        "label": "Web Development",
        "url": "#",
        "port": None,
        "whatItIs": "Specialized Web Development MCP service for enhanced technical workflows.",
        "whatYouCanDo": "Enable autonomous web development operations and data integration within your fleet.",
        "startScript": "web-development-mcp/web_sota/start.ps1",
    },
    {
        "label": "Windows Operations",
        "url": "http://127.0.0.1:10749",
        "port": 10749,
        "whatItIs": "Frontend (was 13001)",
        "whatYouCanDo": "Enable autonomous windows operations operations and data integration within your fleet.",
        "startScript": "windows-operations-mcp/webapp/start.bat",
    },
    {
        "label": "Winrar",
        "url": "http://127.0.0.1:10763",
        "port": 10763,
        "whatItIs": "Frontend (was 13401)",
        "whatYouCanDo": "Enable autonomous winrar operations and data integration within your fleet.",
        "startScript": "winrar-mcp/web_sota/start.ps1",
    },
]
